version: '3.7'
services:
  go-api:
    build: go-api/
    restart: always
    ports:
      - "9999:9999"
  vue:
    build:
      context: vue/
      args:
        - VUE_APP_API_URL
    restart: always
    ports:
      - "8080:8080"

