# 参照：https://vuejs.org/v2/cookbook/dockerize-vuejs-app.html

FROM node:lts-alpine

# 簡易的なhttpサーバーをインストール
RUN npm install -g http-server

# 作業ディレクトリを指定
WORKDIR /app

# package.json、package-lock.json ファイルをコピー
COPY package*.json ./

# 依存関係のあるパッケージをダウンロード
RUN npm install

# ファイルとディレクトリをコピー
COPY . .

# ソースコードをビルド
RUN npm run build

# 使用するポートを公開
EXPOSE 8080

# デフォルトの実行コマンド
CMD [ "http-server", "dist" ]